### PR TITLE
Update lang_en.json

### PR DESCRIPTION
**Pull request by Ejraiel**
Edited for readability, emphasis, and color consistency.

Made the following as a color guide:
ej uessentials colors

### CODE REVIEW

**Comment by leonardosnt** [comment]
Oh, very nice. Thanks :d

**Comment by Ejraiel** [comment]
Glad you like it. =]  :doughnut:

**Comment by Daniil1288** [comment]
Daaang... Fine job, sir. Very nice.

**Comment by leonardosnt** [comment]
You can improve the README.md also. :D

When you want.

**Comment by Ejraiel** [comment]
Cool cool. I plan on doing so, then. =]

**Pull request merged**
