### PR TITLE
Make uEssentials Compile Again

### PR DESCRIPTION
**Pull request by Kr4ken-9**
This is a small PR compared to the other ones, all it does is fix the compile-time errors for uEssentials. Besides that, I may have added a couple files that aren't necessary.

### CODE REVIEW

**Comment by Kr4ken-9** [comment]
Just kidding, now it compiles. And I doubled checked and all of the files added are essential.

**Comment by Kr4ken-9** [comment]
This PR also fixes the error some users are getting:
https://github.com/uEssentials/uEssentials/issues/758
https://github.com/uEssentials/uEssentials/issues/760

**Comment by leonardosnt** [comment]
Thanks! I'm unable to test it, so I would really appreciate if someone could tell my if uEssentials is actually working (loading properly etc)

**Comment by Tortellio** [comment]
yes its working properly

**Pull request merged**
